<?php

namespace Itmar\WpsettingClassPackage;

if (!defined('ABSPATH')) exit;

/**
 * サブディレクトリに設置したサイトを、ドメインのルートURLで表示できるようにする。
 *
 * 書き換えるのは home（サイトアドレス）だけで、siteurl（WordPressアドレス）は
 * 触らない。管理画面もログインURLも siteurl 基準なので、この設定でログインでき
 * なくなることはない。影響が出るのはフロント側だけ。
 *
 * それでもフロントが表示できなくなるのは困るので、
 *   1. 適用できる環境かを保存時に判定し、満たさなければ何も変更せず理由を通知する
 *   2. home を書き換える前にドメインルートへ実際にアクセスし、WordPress が
 *      応答することを確認する
 *   3. 書き換え後にもう一度確認し、応答しなければ自動的に元へ戻す
 * という三段構えにしている。
 */
class ItmarRedirectControl
{
    private static $instance = null;
    private $redirect_option = 'itmar_redirect_to_subdir';
    private $prev_home_option = 'itmar_redirect_prev_home';
    private $error_option = 'itmar_redirect_error';
    private $index_php_path;

    public static function get_instance()
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct()
    {
        // DOCUMENT_ROOT が取れない環境では、意味のないパスを組み立てないよう空にする
        $document_root = isset($_SERVER['DOCUMENT_ROOT'])
            ? untrailingslashit(wp_normalize_path((string) $_SERVER['DOCUMENT_ROOT']))
            : '';
        $this->index_php_path = '' !== $document_root ? $document_root . '/index.php' : '';
        // 設定保存処理
        add_action('admin_init', [$this, 'maybe_apply_redirect']);
        //admin_notices でエラー通知
        add_action('admin_notices', [$this, 'admin_notice_error']);
    }

    /** サイトが置かれているサブディレクトリ名。ルート設置なら空文字。 */
    private function get_subdirectory()
    {
        $parsed = wp_parse_url(get_option('siteurl'));
        return isset($parsed['path']) ? trim($parsed['path'], '/') : '';
    }

    /** ドメインのルートURL */
    private function get_domain_root()
    {
        $parsed = wp_parse_url(get_option('siteurl'));
        $port   = isset($parsed['port']) ? ':' . $parsed['port'] : '';
        return $parsed['scheme'] . '://' . $parsed['host'] . $port . '/';
    }

    /** ドメインルートの index.php がこのプラグインの生成物か */
    private function is_generated_index()
    {
        if ('' === $this->index_php_path || !file_exists($this->index_php_path)) {
            return false;
        }
        return str_contains((string) file_get_contents($this->index_php_path), 'Auto-generated by ItmarRedirectControl');
    }

    /**
     * この設定を適用できる環境かを判定する。
     *
     * @return array{ok:bool, reasons:string[]}
     */
    public function check_requirements()
    {
        $reasons = array();

        if ('' === $this->get_subdirectory()) {
            $reasons[] = esc_html__('This site is not installed in a subdirectory, so this setting is not needed.', 'wpsetting-class-package');
        }

        if ('' === $this->index_php_path) {
            $reasons[] = esc_html__('The domain root could not be determined from the server environment (DOCUMENT_ROOT is empty).', 'wpsetting-class-package');
            return array('ok' => false, 'reasons' => $reasons);
        }

        $root = dirname($this->index_php_path);
        if (!is_dir($root)) {
            /* translators: %s: filesystem path of the domain root. */
            $reasons[] = sprintf(esc_html__('The domain root (%s) was not found.', 'wpsetting-class-package'), $root);
        } elseif (!is_writable($root)) {
            /* translators: %s: filesystem path of the domain root. */
            $reasons[] = sprintf(esc_html__('The domain root (%s) is not writable.', 'wpsetting-class-package'), $root);
        }

        if (file_exists($this->index_php_path) && !$this->is_generated_index()) {
            /* translators: %s: filesystem path of an existing index.php. */
            $reasons[] = sprintf(esc_html__('%s already exists and was not created by this plugin, so it will not be replaced.', 'wpsetting-class-package'), $this->index_php_path);
        }

        return array('ok' => empty($reasons), 'reasons' => $reasons);
    }

    /**
     * ドメインルートで WordPress が応答しているか実際に確かめる。
     *
     * 200 のほか、自サイトのホストへ向いたリダイレクトも「WordPress が動いて
     * いる」と見なす。home を変える前は canonical リダイレクトが返るため。
     * 接続できない場合は false（確認できないなら適用しない）。
     */
    private function domain_root_serves_wp()
    {
        $response = wp_remote_get(
            $this->get_domain_root(),
            array('timeout' => 10, 'sslverify' => false, 'redirection' => 0)
        );

        if (is_wp_error($response)) {
            return false;
        }

        $code = (int) wp_remote_retrieve_response_code($response);
        if (200 === $code) {
            return true;
        }

        if ($code >= 300 && $code < 400) {
            $location = (string) wp_remote_retrieve_header($response, 'location');
            $site_host = strtolower((string) wp_parse_url(get_option('siteurl'), PHP_URL_HOST));
            $loc_host  = strtolower((string) wp_parse_url($location, PHP_URL_HOST));
            return '' !== $loc_host && $loc_host === $site_host;
        }

        return false;
    }

    public function maybe_apply_redirect()
    {
        //ログインユーザーが管理者であること
        if (!current_user_can('manage_options')) return;

        // nonceで想定外のフォームのsubmitを処理しない
        if (
            !isset($_POST['_wpnonce']) ||
            !wp_verify_nonce($_POST['_wpnonce'], 'itmar_setting_nonce')
        ) {
            return;
        }

        // 設定の保存リクエスト時のみ動作
        if (!isset($_POST['submit'])) {
            return;
        }

        $requested = isset($_POST[$this->redirect_option]) ? 1 : 0;
        $current   = (int) get_option($this->redirect_option, 0);

        if ($requested === $current) {
            if ($requested) {
                $this->repair_redirect_index();
            }
            return; // home と復元先は変更しない。
        }

        if ($requested) {
            $this->enable_redirect();
        } else {
            $this->disable_redirect();
        }
    }

    /** 有効のまま保存した場合も検証し、入口ファイルが欠落していれば再生成する。 */
    private function repair_redirect_index()
    {
        $check = $this->check_requirements();
        if (!$check['ok']) {
            update_option($this->error_option, implode(' / ', $check['reasons']));
            return;
        }

        // 既存ファイルは読み込み先を検証するだけで、内容不一致なら上書きしない。
        if (!$this->generate_index_php($this->get_subdirectory())) {
            update_option($this->error_option, esc_html__('Failed to create index.php in the domain root. Nothing was changed.', 'wpsetting-class-package'));
            return;
        }

        // 既に運用中のサイトなので、HTTP確認の失敗を理由に入口を削除しない。
        // 有効化処理の再実行による home / prev_home の上書きも避ける。
        delete_option($this->error_option);
    }

    /** 検証しながら有効化する */
    private function enable_redirect()
    {
        $check = $this->check_requirements();
        if (!$check['ok']) {
            update_option($this->error_option, implode(' / ', $check['reasons']));
            return; // オプションも home も変更しない
        }

        if (!$this->generate_index_php($this->get_subdirectory())) {
            update_option($this->error_option, esc_html__('Failed to create index.php in the domain root. Nothing was changed.', 'wpsetting-class-package'));
            return;
        }

        // home を書き換える前に、ドメインルートが本当にこのサイトを返すか確認する。
        // ここで確認できないまま home を変えると、フロントが表示できなくなる。
        if (!$this->domain_root_serves_wp()) {
            $this->remove_index_php();
            update_option($this->error_option, esc_html__('The domain root did not respond as this site, so the change was not applied. The Site Address is unchanged.', 'wpsetting-class-package'));
            return;
        }

        update_option($this->prev_home_option, get_option('home'));
        update_option('home', $this->get_domain_root());
        update_option($this->redirect_option, 1);

        // 反映後にもう一度確認し、応答しなければ自動的に戻す
        if (!$this->domain_root_serves_wp()) {
            $this->disable_redirect();
            update_option($this->error_option, esc_html__('The domain root stopped responding after the change, so it was reverted automatically.', 'wpsetting-class-package'));
        }
    }

    /** 元の状態に戻す */
    private function disable_redirect()
    {
        $this->remove_index_php();

        $previous = get_option($this->prev_home_option, '');
        update_option('home', '' !== $previous ? $previous : trailingslashit(get_option('siteurl')));
        delete_option($this->prev_home_option);

        update_option($this->redirect_option, 0);
    }

    /** index.php を生成 */
    private function generate_index_php($subdir)
    {
        if (empty($subdir)) return false; // サブディレクトリがないなら不要
        if ('' === $this->index_php_path) return false; // 生成先が特定できない

        // すでに index.php が存在する場合はエラー
        if (file_exists($this->index_php_path)) {
            $contents = file_get_contents($this->index_php_path);

            $pattern = '/require\s+__DIR__\s*\.\s*[\'"]\/\s*' . preg_quote($subdir, '/') . '\s*\/wp-blog-header\.php[\'"];/';
            if (preg_match($pattern, $contents)) {

                // ファイルが存在し、require 文も含まれている
                return true;
            } else {
                // ファイルはあるが、指定の require 文は含まれていない
                return false;
            }
        }

        // index.php 内容
        $content = <<<PHP
            <?php
            /**
            * Auto-generated by ItmarRedirectControl
            */
            define('WP_USE_THEMES', true);
            require __DIR__ . '/{$subdir}/wp-blog-header.php';
            PHP;

        // 書き込み権限確認
        if (!is_writable(dirname($this->index_php_path))) {
            return false;
        }

        // index.php 作成
        return file_put_contents($this->index_php_path, $content) !== false;
    }

    /** ItmarRedirectControl が生成した index.php のみ削除 */
    private function remove_index_php()
    {
        if (
            '' !== $this->index_php_path &&
            file_exists($this->index_php_path) &&
            is_writable($this->index_php_path)
        ) {
            $content = file_get_contents($this->index_php_path);
            if (strpos($content, 'Auto-generated by ItmarRedirectControl') !== false) {
                unlink($this->index_php_path);
            }
        }
    }

    /** 設定画面をレンダリング */
    public function render_settings_section()
    {
        $enabled = get_option($this->redirect_option, 0);

?>
        <h2><?php
            esc_html_e('Redirect Settings', 'wpsetting-class-package');
            ?></h2>
        <table class="form-table">
            <tr>
                <th scope="row"><?php esc_html_e('Redirecting from the domain root URL', 'wpsetting-class-package'); ?></th>
                <td>
                    <label>
                        <input type="checkbox" name="<?php echo esc_attr($this->redirect_option); ?>" value="1" <?php checked($enabled, 1); ?>>
                        <?php esc_html_e('Redirect the domain root URL to this site', 'wpsetting-class-package'); ?>
                    </label>
                    <p class="description"><?php esc_html_e('If this site is installed in a subdirectory, it will also be accessible at the root domain URL.', 'wpsetting-class-package'); ?></p>
                </td>
            </tr>
        </table>

        <?php
    }

    public function admin_notice_error()
    {
        $message = get_option($this->error_option);
        if (!$message) {
            return;
        }
?>
        <div class="notice notice-error is-dismissible">
            <p><strong><?php esc_html_e('Redirect setting was not applied.', 'wpsetting-class-package'); ?></strong></p>
            <p><?php echo esc_html($message); ?></p>
        </div>
<?php
        delete_option($this->error_option); // 表示後に削除
    }
}
